### ISSUE TITLE
Look into orphaned processes when tests fail

### ISSUE THREAD

**Issue by amstrnad** [draperlaboratory/hope-policies#83]
Sometimes when tests fail or maybe timeout, processes are left running. Sometimes they seem to use up system resources. It's possible this is part of why Jenkins runs out of memory occasionally.

**Comment by natestuder** [comment]
It might have something to do with the scripts that run/exit qemu.  Often after having test failures on my machine, I'll do a ps and see several zombie QEMU processes still chugging away.

**Comment by amstrnad** [comment]
`Ctrl+C`ing the tests doesn't kill running tests, but once they finish running, they're gone.
Hitting the timeout doesn't kill the running test, but same as above.

If the test gets into an infinite loop, then it stays running and never ends. One of the exception handlers is an infinite loop. There may be other situations that cause the first two scenarios not to end properly, but I haven't been able to reproduce anything.

**Comment by schirice** [comment]
Started the **isp_run_app** in a new session and make it the group leader. As a result, all the subprocesses spawned by the **isp_run_app** will have the same groupID and thus we could kill them (via the os.killpg call) if the parent times out.
